apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: ohhhhh.co
spec:
 dnsNames:
  - ohhhhh.co
  - "*.ohhhhh.co" 
 issuerRef:
   kind: ClusterIssuer
   name: letsencrypt-dns01 # 引用 ClusterIssuer，指示采用 dns01 方式进行校验
 secretName: mydomain-com-tls # 最终签发出来的证书会保存在这个 Secret 里面
