apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-dns01
    email: tong@ohhhhh.co
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: tong2856@hotmail.com 
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
